Get Topology Manager policy from configz-endpoint
k8stopologyawareschedwg/node-feature-discovery pull request #4
Opened 2021-02-07 08:33 UTC by Tal-or

Co-authored-by: Killian Muldoon <killian.muldoon@intel.com>
Signed-off-by: Killian Muldoon <killian.muldoon@intel.com>
Signed-off-by: titzhak <titzhak@redhat.com>

2021-02-08 07:56 UTC, fromanirh commented
Hey, great first start, please add few lines to explain the rationale anf why we need this PR.

2021-02-08 08:28 UTC, fromanirh reviewed
looks good, some minor comments inside about possibly implicit assumption we may want to make explicit. Please make the commit message less terse, explaining why and how (few lines suffice, no need to write an essay here!). And please add some tests! either unit or e2e.

2021-02-08 08:28 UTC, fromanirh commented on cmd/nfd-topology-updater/main.go
> +	if resourcemonitorArgs.KubeletConfigObtainOpt == "kubelet-config-file" {
maybe we can use constants for "kubelet-config-file" and the other values this option can have

2021-02-08 08:28 UTC, fromanirh commented on pkg/nfd-master/nfd-master.go
> +	if len(r.TopologyPolicy[0]) == 0 {
ok this is because `r.TopologyPolicy` is a slice of strings so, as you pointed out, if we do just `len(r.TopologyPolicy)` and `r.TopologyPolicy[0] == ""` we don't detect the right scenario. But we need to iterate over all the slice and run this check on all items.

2021-02-08 11:26 UTC, swatisehgal requested changes
Nice work, just a few minor comments.

2021-02-08 11:26 UTC, swatisehgal commented on pkg/nfd-master/nfd-master.go
> +	if len(r.TopologyPolicy[0]) == 0 {
+1

2021-02-10 13:02 UTC, fromanirh commented on test/e2e/nfd_topology_updater.go
> +		topologyUpdaterDaemonSet := testutils.NFDTopologyUpdaterDaemonSet(fmt.Sprintf("%s:%s", *dockerRepo, *dockerTag), extraArgs)
extraArgs is often a smell. We should have a separate test fixture + test case which ensure that either
1. the topology-updater is deployed with the option we want to test
2. expects the topology-updater to be deployed with the option we want to test, skipping or failing if this not the case.

We had a chat some time ago (cc @swatisehgal @cynepco3hahue ) about expecting the cluster to be configured vs configuring it in the test fixture, I don't remember the outcome of the discussion but in general I (strongly) lean towards the first option wherever feasible/practical.

2021-02-10 13:02 UTC, fromanirh commented on test/e2e/nfd_topology_updater.go
> +	AssertSharedContextsTests := func() {
a bit too generic. Perhaps `validateTopologyManagerPolicy`? let's capture the intent of this block.

2021-02-10 13:02 UTC, fromanirh commented on test/e2e/nfd_topology_updater.go
> +			extraArgs = append(extraArgs, "--obtain-kubelet-config=configz-endpoint")
same comment as above re: extraArgs.

2021-02-10 16:10 UTC, cynepco3hahue commented on pkg/nfd-master/nfd-master.go
> +	if len(r.TopologyPolicy[0]) == 0 {
Can you please clarify what are we trying to check here? Does it possible that we will have a slice of empty strings here?

2021-02-10 16:10 UTC, cynepco3hahue commented on test/e2e/nfd_topology_updater.go
> +		topologyUpdaterDaemonSet := testutils.NFDTopologyUpdaterDaemonSet(fmt.Sprintf("%s:%s", *dockerRepo, *dockerTag), extraArgs)
IIRC we did not really have any outcome, the fact that the NFD currently create all relevant deployment resources via test fixture, I agree in this case e2e tests do not really verify the deployment YAMLs, but it makes tests more flexible.

I prefer to have all components created via code, and use the same methods under e2e test and also to generate deployment YAMLs(similar to Kubevirt project :) )

2021-02-10 16:10 UTC, cynepco3hahue commented on test/e2e/nfd_topology_updater.go
> +	ginkgo.Context("with single nfd-master pod and custom arguments", func() {
Can you please more specific here, something like
```
with single nfd-master pod and --obtain-kubelet-config=configz-endpoint argument
```

2021-02-10 16:14 UTC, fromanirh commented on test/e2e/nfd_topology_updater.go
> +		topologyUpdaterDaemonSet := testutils.NFDTopologyUpdaterDaemonSet(fmt.Sprintf("%s:%s", *dockerRepo, *dockerTag), extraArgs)
I see the merits of this approach and for NFD I'm fine with either approach the project is already using, IOW, let's do what NFD is doing.

2021-02-11 07:17 UTC, Tal-or commented on cmd/nfd-topology-updater/main.go
> +	var tmPolicy string
In case the condition `if resourcemonitorArgs.KubeletConfigObtainOpt == KubeletFile` evaluates as `false`, `tmPolicy` will be passed as an empty string, see [here](https://github.com/Tal-or/node-feature-discovery/blob/tm_policy_from_configz/cmd/nfd-topology-updater/main.go#L108)

2021-02-11 07:27 UTC, Tal-or commented on pkg/nfd-master/nfd-master.go
> +	if len(r.TopologyPolicy[0]) == 0 {
If user chooses to get Kubelet config via `configz-endpoint`, he/she won't provide the path to Kubelet file as an argument to the `nfd-topology-updater`.
In that case `nfd-topology-updater` won't have the Kubelet config file path, so it will fill `r.TopologyPolicy[0]` with an empty string (see [here](https://github.com/k8stopologyawareschedwg/node-feature-discovery/pull/4/commits/c259264c5f70ed95e91db4f942062bd827f132c0#diff-db555674e432cf63f33489ec5055a17978a4d16c9621dec5fd748ad376a1693dR55) in response to your previous comment).
`r.TopologyPolicy[0] == ""` is the hint for the `nfd-master` to get the Kubelet config via `configz-endpoint`

2021-02-11 07:40 UTC, fromanirh commented on pkg/nfd-master/nfd-master.go
> +	if len(r.TopologyPolicy[0]) == 0 {
I asked for this extra check. I think we need some kind of checking in this field somewhere.

2021-02-11 08:06 UTC, fromanirh commented on test/e2e/nfd_topology_updater.go
> +		topologyUpdaterDaemonSet := testutils.NFDTopologyUpdaterDaemonSet(fmt.Sprintf("%s:%s", *dockerRepo, *dockerTag), extraArgs)
The e2e test improvement can be delayed to a later PR, provided the existing e2e tests cover the basic functionality.

2021-02-15 17:27 UTC, fromanirh reviewed
I think this PR is good in its current design, but I have some reservations about the design proper, which are:
1. we do query the node(/proxies) in a synchronous waywhen we update the topology, creating a dependency cycle node->master->node
2. we do query them each time for an information which rarely changes in the cluster

We can merge this PR, but these concerns needs to be addressed with a followup.

2021-02-18 13:41 UTC, fromanirh commented
After followup discussion:
>     1. we do query the node(/proxies) in a synchronous waywhen we update the topology, creating a dependency cycle node->master->node

1. per NFD arch, only `nfd-master` should connect to the apiserver. We _can_ bypass the apiserver (each `nfd-topology-updater` can connect to its own kubelet) but this require more work e.g. to correctly setup the TLS certs, not worth it now.
2. nesting sync call to each other: issue to be filed to evaluate moving the call to `/configz` a separate goroutine, so the two calls are as independent as possible to each other

>     2. we do query them each time for an information which rarely changes in the cluster

it's hard atm to catch kubelet reboots. Possibly missing kubelet config update, albeit rare as they are expected to be, is worse. We keep it like this atm.

> 
> 
> We can merge this PR, but these concerns needs to be addressed with a followup.

2021-02-18 13:41 UTC, merged